services:
  postgres:
    image: postgres:17.4-alpine
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_LOGIN}
      - POSTGRES_DB=${DATABASE_DB}
    volumes:
      - lang_db:/var/lib/postgresql/data
    networks:
      bridge:
    ports:
      - 5432:5432

  redis:
    image: redis:8.0-alpine
    ports:
      - 6379:6379
    networks:
      bridge:
    volumes:
      - redis_data:/data

  app:
    build: .
    image: main_service
    env_file:
      - .env
    networks:
      bridge:
    depends_on:
      - postgres
      - redis


volumes:
  lang_db:
  redis_data:

networks:
  bridge:
    driver: bridge
